# Generated by Django 3.0.8 on 2020-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jumanji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default='https://place-hold.it/100x60', max_length=200),
            preserve_default=False,
        ),
    ]
