# Generated by Django 3.0.8 on 2020-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jumanji', '0004_auto_20200815_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='company_images'),
        ),
    ]
