# Generated by Django 3.0.8 on 2020-08-16 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_jumanji', '0006_auto_20200815_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('not_in_search', 'Не ищу работу'), ('consideration', 'Рассматриваю предложения'), ('in_search', 'Ищу работу')], max_length=100)),
                ('salary', models.FloatField()),
                ('specialty', models.CharField(choices=[('frontend', 'Фронтенд'), ('backend', 'Бэкенд'), ('gamedev', 'Геймдев'), ('devops', 'Девопс'), ('design', 'Дизайн'), ('products', 'Продукты'), ('management', 'Менеджмент'), ('testing', 'Тестирование')], max_length=100)),
                ('grade', models.CharField(choices=[('intern', 'intern'), ('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior'), ('lead', 'lead')], max_length=100)),
                ('education', models.CharField(choices=[('missing', 'Отсутствует'), ('secondary', 'Среднее'), ('vocational', 'Средне-специальное'), ('incomplete_higher', 'Неполное высшее'), ('higher', 'Высшее')], max_length=100)),
                ('experience', models.CharField(max_length=500)),
                ('portfolio', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
